name: variabler
domain: variabler.no
project: Infrastruktur for Forskning
markdown: kramdown
highlighter: rouge
markdown_ext:  markdown,mkdown,mkdn,mkd,md

timezone: GB
permalink: /blog/:year/:month/:day/:title
# pygments: true
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji
  - jekyll-mentions
